eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

server:
  port: 9401

spring:
  application:
    name: zuul
  redis:
    database: 0
    host: localhost
    port: 6379

zuul:
  ignored-services: '*'
  sensitive-headers:
  routes:
    product:
      path: /products/**
      service-id: product
      strip-prefix: false

    order:
      path: /orders/**
      service-id: order
      strip-prefix: false



